# Generated by Django 2.2.7 on 2019-11-08 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0006_auto_20191108_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='test', max_length=20),
            preserve_default=False,
        ),
    ]
