# Generated by Django 2.2.7 on 2019-11-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0007_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
